#!/usr/bin/env bash

fd_exclude_file="$user_conf_path/fzf/fd_exclude"
fd_show_file="$user_conf_path/fzf/fd_show"

mapfile -t fd_exclude < "$fd_exclude_file"
mapfile -t fd_show < "$fd_show_file"

# echo "Arguments read from fd_exclude_file: ${fd_exclude[*]}"
# echo "Arguments read from fd_show_file: ${fd_show[*]}"

exec fd --type directory "${fd_show[@]}" "${fd_exclude[@]}" --color=always "$@"

