#!/usr/bin/env bash

user_conf_path="${user_conf_path:-"$HOME/.usr_conf"}"

fd_exclude_file="$user_conf_path/fzf/fd_exclude"
fd_options_file="$user_conf_path/fzf/fd_options"

# mapfile -t fd_exclude < "$fd_exclude_file"
mapfile -t fd_options < "$fd_options_file"

# echo "Arguments read from fd_exclude_file: ${fd_exclude[*]}"
# echo "Arguments read from fd_options_file: ${fd_options[*]}"

exec fd --type directory "${fd_options[@]}" --ignore-file "$fd_exclude_file" --color=always "$@"

